name: Unit Tests

on: [push]

jobs:
  phpunit-tests:
    name: PHP ${{ matrix.php-version }} Latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-version: [ '5.6','7.0','7.1','7.2','7.3','7.4' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, curl, json, openssl

      - name: Print PHP version
        run: echo ${{ steps.setup-php.outputs.php-version }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer

      - name: Validate composer.json
        run: composer validate

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run phpunit tests
        run: composer tests
